import { useState, type FormEvent } from "react";
import { Check, Plus } from "@phosphor-icons/react";
import { Button } from "../../components/ui/Button";
import { Field } from "../../components/ui/Field";
import { calculateRecoverySummary } from "../../domain/recovery";
import { id, todayKey } from "../../lib/date";
import { useMettlefieldStore } from "../../store/useMettlefieldStore";

export function RecoveryView() {
  const sleep = useMettlefieldStore((state) => state.sleep); const habits = useMettlefieldStore((state) => state.habits); const addHabit = useMettlefieldStore((state) => state.addHabit); const toggleHabit = useMettlefieldStore((state) => state.toggleHabit); const [open, setOpen] = useState(false); const today = todayKey(); const recent = Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (6 - index)); const key = date.toLocaleDateString("en-CA"); return { key, label: date.toLocaleDateString("en-US", { weekday: "short" }), sleep: sleep.find((item) => item.date === key)?.value }; }); const recentKeys = new Set(recent.map((item) => item.key)); const summary = calculateRecoverySummary(sleep.filter((item) => recentKeys.has(item.date)));
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); addHabit({ id: id(), label: String(data.get("habit")), dates: [] }); event.currentTarget.reset(); setOpen(false); }
  return <div><div className="feature-heading"><div><span className="section-kicker">Recovery</span><h2>Sleep and repeatable habits</h2><p>Use the record to notice patterns. A single score should not run the day.</p></div><Button variant="secondary" onClick={() => setOpen(!open)}><Plus aria-hidden="true" /> Add habit</Button></div><div className="recovery-stats"><div><span>Average sleep</span><strong>{summary.average ? `${summary.average} hr` : "No data"}</strong></div><div><span>Consistency</span><strong>{summary.consistency === null ? "No data" : `${summary.consistency}%`}</strong></div><div><span>Target hit rate</span><strong>{summary.targetHitRate === null ? "No data" : `${summary.targetHitRate}%`}</strong></div></div>{open && <form className="habit-form" onSubmit={submit}><Field label="Habit name" name="habit" required placeholder="Take a lunchtime walk" /><Button type="submit">Save habit</Button></form>}<section className="sleep-week"><span className="section-kicker">Recent nights</span><div>{recent.map((item) => <article key={item.key}><i><b style={{ height: `${Math.min(100, (item.sleep || 0) / 10 * 100)}%` }} /></i><strong>{item.sleep ? `${item.sleep}h` : ""}</strong><span>{item.label}</span></article>)}</div></section><section className="habit-panel"><header><div><span className="section-kicker">Today</span><h3>Daily habits</h3></div><span>{habits.filter((habit) => habit.dates.includes(today)).length} of {habits.length}</span></header>{habits.map((habit) => <button key={habit.id} aria-pressed={habit.dates.includes(today)} className={habit.dates.includes(today) ? "done" : ""} onClick={() => toggleHabit(habit.id, today)}><span>{habit.dates.includes(today) && <Check aria-hidden="true" />}</span><strong>{habit.label}</strong><small>{habit.dates.filter((date) => recent.some((item) => item.key === date)).length}/7 this week</small></button>)}</section></div>;
}
