import { Printer } from "@phosphor-icons/react";
import { Button } from "../../components/ui/Button";
import { buildWeeklyReport } from "../../domain/reports";
import { useMettlefieldStore } from "../../store/useMettlefieldStore";

export function WeeklyReport() {
  const state = useMettlefieldStore(); const dates = Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (6 - index)); return date.toLocaleDateString("en-CA"); }); const report = buildWeeklyReport(state, dates); const loggedDays = new Set(state.foods.filter((item) => dates.includes(item.date)).map((item) => item.date)).size; const activeDays = new Set([...state.workouts, ...state.cardio].filter((item) => dates.includes(item.date)).map((item) => item.date)).size; const habitChecks = state.habits.reduce((sum, habit) => sum + habit.dates.filter((date) => dates.includes(date)).length, 0); const habitTotal = state.habits.length * 7;
  const frequent = Object.values(state.foods.filter((item) => dates.includes(item.date)).reduce<Record<string, { name: string; count: number }>>((acc, food) => { const key = food.name.toLowerCase(); acc[key] = acc[key] ? { ...acc[key], count: acc[key].count + 1 } : { name: food.name, count: 1 }; return acc; }, {})).sort((a, b) => b.count - a.count).slice(0, 5);
  return <div><div className="feature-heading"><div><span className="section-kicker">Seven-day review</span><h2>{dates[0]} to {dates[6]}</h2><p>A compact record of nutrition, training, activity, habits, and recovery.</p></div><Button variant="secondary" onClick={() => window.print()}><Printer aria-hidden="true" /> Print report</Button></div><div className="report-scoreboard"><div><span>Days logged</span><strong>{loggedDays}/7</strong></div><div><span>Active days</span><strong>{activeDays}/7</strong></div><div><span>Workouts</span><strong>{report.workoutCount}</strong></div><div><span>Average sleep</span><strong>{report.recovery.average ? `${report.recovery.average} hr` : "None"}</strong></div></div><div className="report-grid"><section><h3>Nutrition</h3><dl><div><dt>Average calories</dt><dd>{loggedDays ? Math.round(report.nutrition.calories / loggedDays).toLocaleString() : 0} kcal</dd></div><div><dt>Average protein</dt><dd>{loggedDays ? Math.round(report.nutrition.protein / loggedDays) : 0} g</dd></div><div><dt>Training volume</dt><dd>{report.trainingVolume.toLocaleString()}</dd></div></dl></section><section><h3>Habit completion</h3><div className="report-ring" style={{ "--value": `${habitTotal ? habitChecks / habitTotal * 100 : 0}%` } as React.CSSProperties}><strong>{habitTotal ? Math.round(habitChecks / habitTotal * 100) : 0}%</strong></div><p>{habitChecks} of {habitTotal} planned checks completed.</p></section><section><h3>Frequently logged foods</h3>{frequent.length ? <ol>{frequent.map((food) => <li key={food.name}><span>{food.name}</span><strong>{food.count}</strong></li>)}</ol> : <p>No food entries this week.</p>}</section><section><h3>Cardio</h3><dl><div><dt>Sessions</dt><dd>{state.cardio.filter((item) => dates.includes(item.date)).length}</dd></div><div><dt>Minutes</dt><dd>{state.cardio.filter((item) => dates.includes(item.date)).reduce((sum, item) => sum + item.durationMinutes, 0)}</dd></div><div><dt>Sleep target hit</dt><dd>{report.recovery.targetHitRate === null ? "None" : `${report.recovery.targetHitRate}%`}</dd></div></dl></section></div></div>;
}
