import { ArrowRight, Barbell, Check, Drop, ForkKnife, Lightbulb, Moon } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import { Metric } from "../../components/ui/Metric";
import { calculateNutritionTotals } from "../../domain/nutrition";
import { calculateWorkoutStreak } from "../../domain/training";
import { formatDate, todayKey } from "../../lib/date";
import { useMettlefieldStore } from "../../store/useMettlefieldStore";

export function TodayRoute() {
  const state = useMettlefieldStore(); const date = todayKey();
  const nutrition = calculateNutritionTotals(state.foods.filter((entry) => entry.date === date));
  const water = state.water.filter((entry) => entry.date === date).reduce((sum, entry) => sum + entry.value, 0);
  const sleep = [...state.sleep].reverse().find((entry) => entry.date === date)?.value;
  const name = state.profile.name ? `, ${state.profile.name.split(" ")[0]}` : "";
  const recentFoods = state.foods.filter((entry) => entry.date === date).slice(-4).reverse(); const activeDays = new Set([...state.workouts, ...state.cardio].filter((item) => { const days = (Date.now() - new Date(`${item.date}T12:00:00`).getTime()) / 86400000; return days >= 0 && days < 7; }).map((item) => item.date)).size;
  return <section className="route-frame today-route"><header className="route-header"><div><p className="eyebrow">{formatDate()}</p><h1>Good day{name}</h1><p className="lede">Keep the record useful. Log what matters and get on with the day.</p></div><div className="day-stamp"><span>{calculateWorkoutStreak(state.workouts)}</span><small>day training streak</small></div></header>
    <div className="daily-board"><div className="calorie-orbit" style={{ "--progress": `${Math.min(100, nutrition.calories / state.goals.calories * 100)}%` } as React.CSSProperties}><div><strong>{Math.max(0, state.goals.calories - nutrition.calories).toLocaleString()}</strong><span>kcal left</span></div></div><div className="daily-copy"><span className="section-kicker">Daily balance</span><h2>{nutrition.calories ? "You have room to work with." : "Start with your first meal."}</h2><p>{nutrition.calories.toLocaleString()} of {state.goals.calories.toLocaleString()} kcal logged</p><Link className="text-link" to="/log">Open daily log <ArrowRight aria-hidden="true" /></Link></div></div>
    <div className="metric-grid"><Metric label="Protein" value={`${nutrition.protein} g`} detail={`${state.goals.protein} g target`} progress={nutrition.protein / state.goals.protein * 100} /><Metric label="Carbohydrate" value={`${nutrition.carbs} g`} detail={`${state.goals.carbs} g target`} progress={nutrition.carbs / state.goals.carbs * 100} /><Metric label="Fat" value={`${nutrition.fat} g`} detail={`${state.goals.fat} g target`} progress={nutrition.fat / state.goals.fat * 100} /></div>
    <div className="section-heading"><div><span className="section-kicker">Quick record</span><h2>What needs an update?</h2></div></div><div className="quick-grid"><Link to="/log" className="quick-card"><ForkKnife aria-hidden="true" /><div><strong>Meal</strong><span>{nutrition.calories ? "Add another entry" : "Nothing logged yet"}</span></div><ArrowRight aria-hidden="true" /></Link><Link to="/log" className="quick-card"><Drop aria-hidden="true" /><div><strong>Water</strong><span>{water} of {state.goals.water} cups</span></div><ArrowRight aria-hidden="true" /></Link><Link to="/log" className="quick-card"><Moon aria-hidden="true" /><div><strong>Sleep</strong><span>{sleep ? `${sleep} hours` : "Add last night"}</span></div><ArrowRight aria-hidden="true" /></Link><Link to="/train" className="quick-card"><Barbell aria-hidden="true" /><div><strong>Training</strong><span>{state.workouts.some((item) => item.date === date) ? "Session recorded" : "Choose a session"}</span></div><ArrowRight aria-hidden="true" /></Link></div>
    <div className="today-detail-grid"><section className="today-foods"><header><div><span className="section-kicker">Today</span><h2>Recent food</h2></div><Link to="/log">View diary</Link></header>{recentFoods.length ? recentFoods.map((food) => <div key={food.id}><div><strong>{food.name}</strong><span>{food.meal} · {food.serving}</span></div><div><strong>{food.calories} kcal</strong><span>{food.protein} g protein</span></div></div>) : <p>No food entries yet.</p>}<Link className="idea-callout" to="/log?view=ideas"><Lightbulb aria-hidden="true" /><span><strong>Need a meal idea?</strong><small>Browse 52 retained meals with shopping lists and one-step logging.</small></span><ArrowRight aria-hidden="true" /></Link></section><section className="today-habits"><header><div><span className="section-kicker">Habits</span><h2>Small checks</h2></div><span>{state.habits.filter((habit) => habit.dates.includes(date)).length}/{state.habits.length}</span></header>{state.habits.map((habit) => <button key={habit.id} aria-pressed={habit.dates.includes(date)} className={habit.dates.includes(date) ? "done" : ""} onClick={() => state.toggleHabit(habit.id, date)}><span>{habit.dates.includes(date) && <Check aria-hidden="true" />}</span>{habit.label}</button>)}<div className="week-context"><span>Active days this week</span><strong>{activeDays}/7</strong></div></section></div>
  </section>;
}
