import { parseGarminExport } from "./garmin";

describe("Garmin import", () => {
  it("reads activity CSV exports", () => { const result = parseGarminExport("Activity Type,Date,Duration,Calories\nRunning,2026-08-20,30,320", "Activities.csv"); expect(result.cardio[0]).toMatchObject({ type: "Running", durationMinutes: 30, calories: 320 }); });
  it("reads quoted commas and clock durations with stable ids", () => { const source = 'Activity Type,Date,Duration,Notes\n"Running, trail",2026-08-20,01:30:00,"Hilly, steady"'; const first = parseGarminExport(source, "a.csv"); const second = parseGarminExport(source, "renamed.csv"); expect(first.cardio[0]).toMatchObject({ type: "Running, trail", durationMinutes: 90 }); expect(first.cardio[0].id).toBe(second.cardio[0].id); });
  it("converts Garmin JSON meters to the selected display unit", () => { const source = JSON.stringify([{ activityId: 1, calendarDate: "2026-08-20", durationInSeconds: 1800, distance: 5000 }]); expect(parseGarminExport(source, "activities.json", "metric").cardio[0].distance).toBe(5); expect(parseGarminExport(source, "activities.json", "imperial").cardio[0].distance).toBeCloseTo(3.107, 3); });
  it("keeps otherwise identical activities with different start times", () => { const source = JSON.stringify({ activityList: [{ startTimeLocal: "2026-08-20T08:00:00", durationInSeconds: 1800, distance: 5000 }, { startTimeLocal: "2026-08-20T18:00:00", durationInSeconds: 1800, distance: 5000 }] }); const result = parseGarminExport(source, "activities.json"); expect(result.cardio).toHaveLength(2); expect(result.cardio[0].id).not.toBe(result.cardio[1].id); });
  it("keeps provider-less ids stable when JSON rows are reordered", () => { const rows = [{ startTimeLocal: "2026-08-20T08:00:00", durationInSeconds: 1800, distance: 5000 }, { startTimeLocal: "2026-08-20T18:00:00", durationInSeconds: 1200, distance: 3000 }]; const first = parseGarminExport(JSON.stringify(rows), "activities.json").cardio.map((item) => item.id).sort(); const second = parseGarminExport(JSON.stringify([...rows].reverse()), "activities.json").cardio.map((item) => item.id).sort(); expect(first).toEqual(second); });
  it("reports unsupported files", () => { expect(parseGarminExport("not useful", "file.txt").warnings).toHaveLength(1); });
});
