import { useState } from "react";
import { Check, Minus, Plus } from "@phosphor-icons/react";
import { Button } from "../../components/ui/Button";
import type { Exercise } from "../../exercises/types";
import { id, todayKey } from "../../lib/date";
import { useMettlefieldStore } from "../../store/useMettlefieldStore";

export function ActiveWorkout({ exercises, onRemove, onFinish }: { exercises: Exercise[]; onRemove: (id: string) => void; onFinish: () => void }) {
  const addWorkout = useMettlefieldStore((state) => state.addWorkout); const [sets, setSets] = useState<Record<string, Array<{ reps: number; weight: number }>>>({}); const [started] = useState(Date.now());
  function addSet(exerciseId: string) { setSets((current) => ({ ...current, [exerciseId]: [...(current[exerciseId] || []), { reps: 8, weight: 0 }] })); }
  function finish() { addWorkout({ id: id(), date: todayKey(), title: exercises.length === 1 ? exercises[0].name : "Training session", durationMinutes: Math.max(1, Math.round((Date.now() - started) / 60000)), exercises: exercises.map((exercise) => ({ exerciseId: exercise.id, name: exercise.name, primaryMuscles: exercise.primaryMuscles, sets: (sets[exercise.id] || []).map((set) => ({ ...set, id: id(), completed: true })) })) }); onFinish(); }
  const hasSets = Object.values(sets).some((items) => items.length > 0);
  return <section className="workout-sheet"><header><div><span className="section-kicker">In progress</span><h2>Current session</h2></div><Button disabled={!exercises.length || !hasSets} onClick={finish}><Check aria-hidden="true" /> Finish</Button></header>{exercises.length ? exercises.map((exercise) => <article className="workout-exercise" key={exercise.id}><div className="workout-exercise-title"><div><strong>{exercise.name}</strong><span>{exercise.primaryMuscles.map((item) => item.replaceAll("_", " ")).join(", ")}</span></div><button className="icon-button" aria-label={`Remove ${exercise.name}`} onClick={() => onRemove(exercise.id)}><Minus aria-hidden="true" /></button></div><div className="set-table"><div><span>Set</span><span>Weight</span><span>Reps</span></div>{(sets[exercise.id] || []).map((set, index) => <div key={index}><span>{index + 1}</span><input aria-label={`${exercise.name} set ${index + 1} weight`} type="number" min="0" value={set.weight} onChange={(event) => setSets((current) => ({ ...current, [exercise.id]: current[exercise.id].map((item, itemIndex) => itemIndex === index ? { ...item, weight: Number(event.target.value) } : item) }))} /><input aria-label={`${exercise.name} set ${index + 1} reps`} type="number" min="1" value={set.reps} onChange={(event) => setSets((current) => ({ ...current, [exercise.id]: current[exercise.id].map((item, itemIndex) => itemIndex === index ? { ...item, reps: Number(event.target.value) } : item) }))} /></div>)}</div><Button variant="quiet" onClick={() => addSet(exercise.id)}><Plus aria-hidden="true" /> Add set</Button></article>) : <p className="sheet-empty">Choose a movement from the library to begin.</p>}</section>;
}
