import { useEffect, useState } from "react";
import { Check, Minus, Plus, Timer } from "@phosphor-icons/react";
import { Button } from "../../components/ui/Button";
import type { Exercise } from "../../exercises/types";
import { id, todayKey } from "../../lib/date";
import { useMettlefieldStore } from "../../store/useMettlefieldStore";

export function ActiveWorkout({ exercises, onRemove, onFinish }: { exercises: Exercise[]; onRemove: (id: string) => void; onFinish: (summary: string) => void }) {
  const addWorkout = useMettlefieldStore((state) => state.addWorkout); const workouts = useMettlefieldStore((state) => state.workouts); const units = useMettlefieldStore((state) => state.profile.units === "metric" ? "kg" : "lb"); const [sets, setSets] = useState<Record<string, Array<{ reps: number; weight: number }>>>({}); const [started, setStarted] = useState(Date.now()); const [rest, setRest] = useState(0);
  useEffect(() => { if (rest <= 0) return; const timer = window.setInterval(() => setRest((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [rest > 0]);
  function addSet(exerciseId: string) { setSets((current) => ({ ...current, [exerciseId]: [...(current[exerciseId] || []), { reps: 8, weight: 0 }] })); }
  function finish() { const durationMinutes = Math.max(1, Math.round((Date.now() - started) / 60000)); const setCount = Object.values(sets).flat().length; addWorkout({ id: id(), date: todayKey(), title: exercises.length === 1 ? exercises[0].name : "Training session", durationMinutes, exercises: exercises.map((exercise) => ({ exerciseId: exercise.id, name: exercise.name, primaryMuscles: exercise.primaryMuscles, sets: (sets[exercise.id] || []).map((set) => ({ ...set, id: id(), completed: true })) })) }); setSets({}); setStarted(Date.now()); setRest(0); onFinish(`${setCount} sets saved in a ${durationMinutes}-minute session.`); }
  const validSets = Object.values(sets).some((items) => items.length > 0) && Object.values(sets).flat().every((set) => Number.isFinite(set.reps) && set.reps > 0 && Number.isFinite(set.weight) && set.weight >= 0);
  return <section className="workout-sheet"><header><div><span className="section-kicker">In progress</span><h2>Current session</h2></div><Button disabled={!exercises.length || !validSets} onClick={finish}><Check aria-hidden="true" /> Finish</Button></header>{rest > 0 && <div className="rest-timer" role="timer"><Timer aria-hidden="true" /> Rest {Math.floor(rest / 60)}:{String(rest % 60).padStart(2, "0")} <button onClick={() => setRest(0)}>Skip</button></div>}{exercises.length ? exercises.map((exercise) => { const previous = [...workouts].reverse().flatMap((workout) => workout.exercises).find((item) => item.exerciseId === exercise.id || item.name === exercise.name); return <article className="workout-exercise" key={exercise.id}><div className="workout-exercise-title"><div><strong>{exercise.name}</strong><span>{exercise.primaryMuscles.map((item) => item.replaceAll("_", " ")).join(", ")}</span>{previous?.sets.length ? <small>Last: {previous.sets.map((set) => `${set.weight} ${units} × ${set.reps}`).join(" · ")}</small> : null}</div><button className="icon-button" aria-label={`Remove ${exercise.name}`} onClick={() => onRemove(exercise.id)}><Minus aria-hidden="true" /></button></div><div className="set-table"><div><span>Set</span><span>Weight</span><span>Reps</span></div>{(sets[exercise.id] || []).map((set, index) => <div key={index}><span>{index + 1}</span><input aria-label={`${exercise.name} set ${index + 1} weight`} type="number" min="0" value={set.weight} onChange={(event) => setSets((current) => ({ ...current, [exercise.id]: current[exercise.id].map((item, itemIndex) => itemIndex === index ? { ...item, weight: Number(event.target.value) } : item) }))} /><input aria-label={`${exercise.name} set ${index + 1} reps`} type="number" min="1" value={set.reps} onChange={(event) => setSets((current) => ({ ...current, [exercise.id]: current[exercise.id].map((item, itemIndex) => itemIndex === index ? { ...item, reps: Number(event.target.value) } : item) }))} /></div>)}</div><div className="button-row"><Button variant="quiet" onClick={() => addSet(exercise.id)}><Plus aria-hidden="true" /> Add set</Button><Button variant="quiet" onClick={() => setRest(90)}><Timer aria-hidden="true" /> Rest 1:30</Button></div></article>; }) : <p className="sheet-empty">Choose a movement from the library to begin.</p>}</section>;
}
