import { useState, type FormEvent } from "react";
import { Button } from "../../components/ui/Button";
import { Field } from "../../components/ui/Field";
import { estimateOneRepMax } from "../../domain/training";
import { useMettlefieldStore } from "../../store/useMettlefieldStore";

export function StrengthProgress() {
  const workouts = useMettlefieldStore((state) => state.workouts); const manual = useMettlefieldStore((state) => state.manualMaxes); const setManualMax = useMettlefieldStore((state) => state.setManualMax); const [message, setMessage] = useState("");
  const derived = workouts.reduce<Record<string, number>>((records, workout) => { workout.exercises.forEach((exercise) => exercise.sets.forEach((set) => { const estimate = estimateOneRepMax(set.weight, set.reps) || 0; records[exercise.name] = Math.max(records[exercise.name] || 0, estimate); })); return records; }, {}); const records = Object.fromEntries([...new Set([...Object.keys(derived), ...Object.keys(manual)])].map((exercise) => [exercise, Math.max(derived[exercise] || 0, manual[exercise] || 0)])); const ranked = Object.entries(records).sort((a, b) => b[1] - a[1]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setManualMax(String(data.get("exercise")), Number(data.get("value"))); setMessage("Strength record saved."); event.currentTarget.reset(); }
  return <div><div className="feature-heading"><div><span className="section-kicker">Strength records</span><h2>Estimated and entered maxes</h2><p>Estimates use the Epley formula. They are a training reference, not a testing requirement.</p></div></div>{message && <div className="inline-notice" role="status">{message}</div>}<form className="record-form" onSubmit={submit}><Field label="Exercise" name="exercise" required placeholder="Barbell Back Squat" /><Field label="One-rep max" name="value" type="number" min="1" step="0.5" required /><Button type="submit">Save record</Button></form><div className="record-list">{ranked.length ? ranked.map(([exercise, value], index) => <div key={exercise}><span>{String(index + 1).padStart(2, "0")}</span><strong>{exercise}</strong><div><b>{Math.round(value * 10) / 10}</b><small>{useMettlefieldStore.getState().profile.units === "metric" ? "kg" : "lb"} estimated 1RM</small></div></div>) : <p>No strength records yet. Finish weighted sets or enter a known max above.</p>}</div></div>;
}
