import { useState, type FormEvent } from "react";
import { CalendarDots, PencilSimple, Play, Plus, Trash } from "@phosphor-icons/react";
import { Button } from "../../components/ui/Button";
import { Field } from "../../components/ui/Field";
import type { Plan } from "../../domain/types";
import { exerciseRepository } from "../../exercises/RepDbExerciseRepository";
import { id } from "../../lib/date";
import { useMettlefieldStore } from "../../store/useMettlefieldStore";

const templates = [
  { name: "Three-day full body", detail: "A repeatable squat, press, pull, hinge, and trunk structure.", days: [["squat", "bench-press", "wide-grip-seated-cable-row"], ["romanian-deadlift", "ohp", "lat-pulldown"], ["leg-press", "incline-bench-press", "kneeling-cable-row"]] },
  { name: "Four-day upper and lower", detail: "Two upper and two lower sessions with measured weekly volume.", days: [["bench-press", "wide-grip-seated-cable-row", "lateral-raise"], ["squat", "romanian-deadlift", "standing-calf-raise"], ["ohp", "lat-pulldown", "bicep-curl"], ["leg-press", "leg-curl", "hip-thrust"]] },
  { name: "Strength foundation", detail: "Three sessions centered on the major barbell movement patterns.", days: [["squat", "bench-press"], ["deadlift", "ohp"], ["squat", "bench-press", "barbell-row"]] },
];
const resolve = (name: string) => exerciseRepository.search().find((exercise) => exercise.name.toLowerCase() === name.toLowerCase())?.id;
const namesFor = (ids: string[]) => ids.map((exerciseId) => exerciseRepository.getById(exerciseId)?.name).filter(Boolean).join(", ");
const idsFor = (value: FormDataEntryValue | null) => String(value || "").split(",").map((item) => resolve(item.trim())).filter(Boolean) as string[];

export function WorkoutPlans({ onStart }: { onStart: (exerciseIds: string[], label: string) => void }) {
  const plans = useMettlefieldStore((state) => state.plans); const activePlanId = useMettlefieldStore((state) => state.activePlanId); const addPlan = useMettlefieldStore((state) => state.addPlan); const updatePlan = useMettlefieldStore((state) => state.updatePlan); const removePlan = useMettlefieldStore((state) => state.removePlan); const setActivePlan = useMettlefieldStore((state) => state.setActivePlan); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Plan>(); const [message, setMessage] = useState("");
  function saveTemplate(template: typeof templates[number]) { const plan = { id: id(), name: template.name, days: template.days.map((exerciseIds, index) => ({ name: `Day ${index + 1}`, exerciseIds })) }; addPlan(plan); setActivePlan(plan.id); setMessage(`${plan.name} is now your active plan.`); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const exerciseIds = idsFor(data.get("movements")); const plan = { id: id(), name: String(data.get("name")), days: [{ name: String(data.get("dayName")) || "Day 1", exerciseIds }] }; addPlan(plan); setActivePlan(plan.id); event.currentTarget.reset(); setOpen(false); setMessage(`Saved ${exerciseIds.length} matched movements. You can start the session below.`); }
  function saveEdit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const data = new FormData(event.currentTarget); const updated = { ...editing, name: String(data.get("name")), days: editing.days.map((day, index) => index === 0 ? { name: String(data.get("dayName")), exerciseIds: idsFor(data.get("movements")) } : day) }; updatePlan(updated); setEditing(undefined); setMessage(`${updated.name} was updated.`); }
  return <div><div className="feature-heading"><div><span className="section-kicker">Programs</span><h2>Give the week a structure</h2><p>Save a template or build a session from exercise names, then launch it directly into the workout log.</p></div><Button onClick={() => setOpen(!open)}><Plus aria-hidden="true" /> New plan</Button></div>{message && <div className="inline-notice" role="status">{message}</div>}{open && <form className="plan-form surface" onSubmit={submit}><Field label="Plan name" name="name" required placeholder="Autumn strength block" /><Field label="Day name" name="dayName" required placeholder="Upper A" /><Field label="Movements" name="movements" required placeholder="Barbell Bench Press, Kneeling Cable Row, Dumbbell Lateral Raise" /><Button type="submit">Save and activate</Button></form>}{editing && <form className="plan-form surface" onSubmit={saveEdit}><Field label="Plan name" name="name" required defaultValue={editing.name} /><Field label="Day name" name="dayName" required defaultValue={editing.days[0].name} /><Field label="Movements" name="movements" required defaultValue={namesFor(editing.days[0].exerciseIds)} /><div className="button-row"><Button type="submit">Save changes</Button><Button variant="secondary" onClick={() => setEditing(undefined)}>Cancel</Button></div></form>}<div className="plan-grid">{templates.map((template) => <article key={template.name}><CalendarDots aria-hidden="true" /><h3>{template.name}</h3><p>{template.detail}</p><button onClick={() => saveTemplate(template)}>Save and use template</button></article>)}</div>{plans.length > 0 && <section className="saved-plans"><span className="section-kicker">Saved plans</span>{plans.map((plan) => <div key={plan.id}><div><strong>{plan.name}{activePlanId === plan.id ? " · Active" : ""}</strong><span>{plan.days.length} training {plan.days.length === 1 ? "day" : "days"}</span></div>{plan.days.map((day) => <Button key={day.name} variant="secondary" disabled={!day.exerciseIds.length} onClick={() => onStart(day.exerciseIds, `${plan.name}: ${day.name}`)}><Play aria-hidden="true" /> Start {day.name}</Button>)}<Button variant="quiet" onClick={() => setEditing(plan)}><PencilSimple aria-hidden="true" /> Edit</Button><Button variant="quiet" onClick={() => { removePlan(plan.id); setMessage(`${plan.name} was deleted.`); }}><Trash aria-hidden="true" /> Delete</Button>{activePlanId !== plan.id && <button onClick={() => setActivePlan(plan.id)}>Make active</button>}</div>)}</section>}</div>;
}
